### ISSUE TITLE
Youtube Share doesn't work for participants in Chrome

### ISSUE THREAD

**Issue by blainegarrett** [gatteo/react-jitsi#5]
I'm researching this issue for my own implementation but it seems to affect yours as well. 

The youtube iframe and the jitsi iframe are not playing nicely with security it seems. 
The youtube video plays fine for the person that shares it, but it won't play for others if they are in Chrome. 

Sometimes there is no error, but when there is, it is something similar to: Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://meet.jit.si').

I'm in desperate need of a solution, so if I find one, I will share it with you. Cheers.

**Comment by gatteo** [comment]
Hi @blainegarrett, 
I was not able to reproduce the bug you are talking about.
Honestly I'm not really sure of what I can do to help.
Have you tried filing an issue on the [Jitsi Meet community forum?](https://community.jitsi.org/)
